name: Hello World
author: timbo
description: Hello dog
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "bob"
outputs:
  time:
    description: "the greeting time"
runs:
  using: "node12"
  main: "index.js"