name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        name: Cache node_modules
        with:
          path: ~/.npm
          key: ${{runner.os}}-timbo-${{ hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-timbo-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn test --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: yarn build
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain ceaseless-adjustment.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
